# Generated by Django 5.2 on 2025-04-13 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Template Category',
                'verbose_name_plural': 'Template Categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='templator_t_slug_3a55e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('zip_file', models.FileField(help_text='Upload a ZIP file containing template files.', upload_to='template_archives/')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('preview_image', models.ImageField(blank=True, help_text='Optional preview image for this template.', null=True, upload_to='template_previews/')),
                ('extraction_path', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_templates', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='templator.templatecategory')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-date_uploaded'],
                'indexes': [models.Index(fields=['slug'], name='templator_t_slug_ecd811_idx'), models.Index(fields=['is_active'], name='templator_t_is_acti_dcb9c2_idx'), models.Index(fields=['date_uploaded'], name='templator_t_date_up_2d1f42_idx'), models.Index(fields=['category'], name='templator_t_categor_76ac80_idx')],
            },
        ),
    ]
