# Generated by Django 5.2 on 2025-04-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='detected_framework',
            field=models.CharField(blank=True, help_text='Framework detected by the analyzer (e.g., django, react, html)', max_length=50, null=True),
        ),
    ]
